db:
  host: 119.29.87.223
  port: 3306
  user: root
  password: 'dceb66c7d2408b87f9cb5bcbd16316f59c1ddf06e4837297b9c2ffe08fa1f5504dc4821d4628'
  dbname: shichang
  dialect: mysql
  key: 'shichang'

ColumnMap:
  NumberFlag: "磅单编号"
  DateStr: "首次称重日期"
  TimeStr: "毛重时间"
  CarNumber: "车号"
  ShopNumber: "货物名称"
  GrossWeight: "毛重"
  TareWeight: "皮重"
  NetWeight: "净重"
  Vendor: "收货单位"
  SendOutDept: "发货单位"